urls.py
from django.conf.urls import include, url

# Uncomment the next two lines to enable the admin:
import django.contrib.admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
django.contrib.admin.autodiscover()

import common.views
import bracelet.views
import admin.views
import ocomments.views
import django.contrib.auth.views

urlpatterns = [

    # MODULE COMMON
    url(r'^$', common.views.index, name = 'home'),
    url(r'^login/?$', common.views.login_user, name = 'login_user'),
    url(r'^logout/?$', common.views.logout_user),
    url(r'^facebook_login/?$', common.views.facebook_login),
    url(r'^facebook_login_success/?$', common.views.facebook_login_success),
    url(r'^search/?$', common.views.search),
    url(r'^register/?$', common.views.register),
    url(r'^profile/?$', common.views.userprofile),
    url(r'^user/(?P<user_name>.*)', common.views.user),
    url(r'^about/?$', common.views.about),
    url(r'^privacypolicy/?$', common.views.privacypolicy),
    url(r'^lang/(?P<lang>\w+)', common.views.setlang),
    url(r'^contact/success/?$', common.views.contact_success),

    # MODULE BRACELET
    url(r'^bracelet/photos/(?P<bracelet_id>\d+)/?$', bracelet.views.photos),
    url(r'^bracelet/photoUpload/(?P<bracelet_id>\d+)', bracelet.views.photo_upload),
    url(r'^bracelet/photo/remove/(?P<photo_id>\d+)', bracelet.views.delete_photo),
    url(r'^bracelet/remove/(?P<bracelet_id>\d+)/?$', bracelet.views.delete_bracelet),
    url(r'^bracelet/rate/(?P<bracelet_id>\d+)/(?P<bracelet_rate>\d+)/?$', bracelet.views.rate),
    url(r'^bracelet/rate/remove/(?P<rate_id>\d+)', bracelet.views.delete_rate),
    url(r'^bracelet/change_status/(?P<bracelet_id>\d+)$', bracelet.views.change_status),
    url(r'^bracelet/generate/(?P<pattern_text>.+)/(?P<text_height>.+)/?$', bracelet.views.generate_text_pattern),
    url(r'^bracelet/delete/(?P<bracelet_id>\d+)/?$', bracelet.views.delete_bracelet),
    url(r'^bracelet/edit/(?P<bracelet_id>\d+)/?$', bracelet.views.edit_bracelet),
    url(r'^bracelet/accept/(?P<bracelet_id>\d+)/(?P<bracelet_status>\-?\d?)/?$', bracelet.views.accept),
    url(r'^add/(?P<bracelet_type>.*)/?$', bracelet.views.add),
    url(r'^addpattern/?$', bracelet.views.addpattern),
    url(r'^bracelet/(?P<bracelet_url>.+)?$', bracelet.views.bracelet),

    # MODULE COMMENT
    url(r'^comments/(?P<bracelet_id>\d+)/$', ocomments.views.pattern_comments),
    url(r'^comments/post/$', ocomments.views.pattern_comments_post),
    url(r'^comments/posted/$', ocomments.views.pattern_comments_posted),
    url(r'^comments/', include('django_comments.urls')),

    # MODULE ADMIN
    url(r'admin/manage_bracelets/?', admin.views.manage_bracelets),

    # Uncomment the admin/doc line below to enable admin documentation:  
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^password_change/?$', django.contrib.auth.views.password_change, name = 'password_change'),
    url(r'^password_change/done/?$', django.contrib.auth.views.password_change_done, name = 'password_change_done'),
    url(r'^password_reset/?$', django.contrib.auth.views.password_reset, name = 'password_reset'),
    url(r'^password_reset/done/?$', django.contrib.auth.views.password_reset_done, name = 'password_reset_done'),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/?$',
        django.contrib.auth.views.password_reset_confirm,
        name = 'password_reset_confirm'),
    url(r'^reset/done/?$', django.contrib.auth.views.password_reset_complete, name = 'password_reset_complete'),

    # Uncomment the next line to enable the admin:
    url(r'^superadmin/', include(django.contrib.admin.site.urls)),
]

urlpatterns += staticfiles_urlpatterns()

common/models.py
'''
Created on Mar 15, 2012

@author: agnis
'''

from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.ForeignKey(User, unique=True)
    fb_username = models.CharField(max_length=100)
    fb_name = models.CharField(max_length=100)

common/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.utils.translation import ugettext as _


class UserCreationFormExtended(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(UserCreationFormExtended, self).__init__(*args, **kwargs)
        self.fields['email'].required = True

    class Meta:
        model = User
        fields = ('username', 'email')


class ContactForm(forms.Form):
    subject = forms.CharField(label=_("Subject"), max_length=100, required=True)
    sender = forms.EmailField(label=_("Sender"), required=True)
    message = forms.CharField(label=_("Message"), widget=forms.Textarea, required=True)

common/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render
from common.models import UserProfile
from bracelet.models import Photo, Rate, BraceletCategory, Bracelet
from django.utils.translation import ugettext as _
from common import captcha
from django.conf import settings
from django.contrib.auth.models import User
from common.forms import UserCreationFormExtended, ContactForm
from django.http import HttpResponseRedirect
# from django.core.mail import send_mail
from common.bracelet_tools import get_colors, find_bracelets, get_all_bracelets
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth import authenticate, login, logout
from pyfb.pyfb import Pyfb
from common.utils import FacebookBackend
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import EmailMessage
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def get_context(request):
    context = {'loginform': AuthenticationForm(), "FACEBOOK_APP_ID": settings.FACEBOOK_APP_ID}
    if request.user.is_authenticated():
        try:
            context['userprofile'] = UserProfile.objects.get(user=request.user)
        except ObjectDoesNotExist:
            pass
    return context


def register(request):
    form = None
    if request.method == 'POST':
        captcha_response = captcha.submit(request.POST['recaptcha_challenge_field'],
                    request.POST['recaptcha_response_field'], settings.RECAPTCHA_PRIVATE_KEY,
                    request.META['REMOTE_ADDR'])
        if captcha_response.is_valid:
            form = UserCreationFormExtended(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, _('Success! You can log in now.'))
                return HttpResponseRedirect('/')
            else:
                messages.error(request, _("An error has occured. Correct entered data."))
        else:
            messages.error(request, _("Wrong captcha, try again."))
    form = UserCreationFormExtended(request.POST)
    context = get_context(request)
    context.update({'form': form, 'captcha': captcha.displayhtml(settings.RECAPTCHA_PUBLIC_KEY)})
    return render(request, "common/register.html", context)

@login_required
def userprofile(request):
    if request.user.is_authenticated():
        bracelets = get_all_bracelets(0, request.user, False)
        bracelets_accepted = []
        bracelets_not_accepted = []
        bracelets_private = []
        bracelets_rejected = [] # FIXME
        for br in bracelets:
            if not br.public:
                bracelets_private.append(br)
            if br.accepted:
                bracelets_accepted.append(br)
            else:
                bracelets_not_accepted.append(br)

        photos = request.user.photos
        photos_accepted = []
        photos_not_accepted = []
        for p in photos.all():
            if p.accepted:
                photos_accepted.append(p)
            else:
                photos_not_accepted.append(p)

        context = get_context(request)
#        context['bracelets_accepted'] = Bracelet.objects.accepted(request.user)
#        context['bracelets_not_accepted'] = Bracelet.objects.waiting(request.user)
#        context['bracelets_rejected'] = Bracelet.objects.rejected(request.user)
#        context['bracelets_private'] = Bracelet.objects.private(request.user)
        context['bracelets_accepted'] = bracelets_accepted
        context['bracelets_not_accepted'] = bracelets_not_accepted
        context['bracelets_private'] = bracelets_private
        context['bracelets_rejected'] = bracelets_rejected
        context['photos_accepted'] = photos_accepted
        context['photos_not_accepted'] = photos_not_accepted
        context['rates'] = Rate.objects.filter(user=request.user)
        return render(request, "common/userprofile.html", context)
    else:
        messages.error(request, _('You need to be logged in.'))
        return HttpResponseRedirect('/')


def user(request, user_name):
    try:
        user = User.objects.get(username=user_name)
    except ObjectDoesNotExist:
        messages.error(request, _('There is no user with login: {0}').format(user_name))
        return HttpResponseRedirect('/')

    context = get_context(request)
    context['user_content'] = user
    context['bracelets'] = get_all_bracelets(0, user)
    context['photos'] = user.photos.filter(accepted=True)
    return render(request, 'common/user.html', context)


def about(request, context={}):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        captcha_response = captcha.submit(request.POST['recaptcha_challenge_field'],
                    request.POST['recaptcha_response_field'], settings.RECAPTCHA_PRIVATE_KEY,
                    request.META['REMOTE_ADDR'])
        if captcha_response.is_valid:
            if form.is_valid():
                subject = form.cleaned_data['subject']
                msg_content = form.cleaned_data['message']
                sender = form.cleaned_data['sender']
                receiver = ['aga@ohiboka.com']
                EmailMessage(subject, msg_content, sender, receiver,
                             headers={'Reply-To': sender}).send()
                # send_mail(subject, msg_content, sender, receiver)
                return HttpResponseRedirect('/contact/success/')
            else:
                messages.error(request, _("An error has occured. Correct entered data."))
                # return about(request, {'subject':
                # form.cleaned_data['subject'], 'msg_content':
                # form.cleaned_data['message'], 'sender':
                # form.cleaned_data['sender']})
                context.update(get_context(request))
                context.update({'contactform': form, 'captcha':
                        captcha.displayhtml(settings.RECAPTCHA_PUBLIC_KEY)})
                return render(request, 'common/about.html', context)
        else:
            messages.error(request, _('Wrong captcha.'))
            # return about(request, {'subject': form.cleaned_data['subject'],
            # 'msg_content': form.cleaned_data['message'], 'sender':
            # form.cleaned_data['sender']})
            context.update(get_context(request))
            context.update({'contactform': form, 'captcha':
                        captcha.displayhtml(settings.RECAPTCHA_PUBLIC_KEY)})
            return render(request, 'common/about.html', context)
    else:
        form = ContactForm()
    context.update(get_context(request))
    context.update({'contactform': form, 'captcha': captcha.displayhtml(settings.RECAPTCHA_PUBLIC_KEY)})
    return render(request, 'common/about.html', context)


def privacypolicy(request):
    return render(request, 'common/privacypolicy.html',
                              get_context(request))


def index(request, context_={}):
    bracelets = get_all_bracelets(0)
    paginator = Paginator(bracelets, 9)
    page = request.GET.get('page')
    if not page:
        page = 1
    try:
        bracelets = paginator.page(page)
    except PageNotAnInteger:
        bracelets = paginator.page(1)
    except EmptyPage:
        bracelets = paginator.page(paginator.num_pages)

    context = get_context(request)
    context.update(context_)
    context.update({
        'patterns': bracelets,
        'colors': get_colors(),
        'categories': BraceletCategory.objects.all(),
    })

    return render(request, 'common/index.html', context)


def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/')


def login_user(request):
    if 'username' in request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None and user.is_active:
            login(request, user)
            messages.success(request, _('You are logged in now'))
            if not request.POST.get('remember_me', None):
                request.session.set_expiry(0)
        return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')


def facebook_login(request):
    facebook = Pyfb(settings.FACEBOOK_APP_ID)
    facebook.set_permissions("")
    return HttpResponseRedirect(facebook.get_auth_code_url(redirect_uri=settings.FACEBOOK_REDIRECT_URL))


# This view must be refered in your FACEBOOK_REDIRECT_URL. For example:
# http://www.mywebsite.com/facebook_login_success/
def facebook_login_success(request):
    code = request.GET.get('code')
    facebook = Pyfb(settings.FACEBOOK_APP_ID)
    facebook.set_permissions("")
    facebook.get_access_token(settings.FACEBOOK_SECRET_KEY, code,
                              redirect_uri=settings.FACEBOOK_REDIRECT_URL)
    me = facebook.get_myself()
    authenticator = FacebookBackend()
    user = authenticator.authenticate(me)
    login(request, user)
    return HttpResponseRedirect('/')


def setlang(request, lang):
    request.session['django_language'] = lang
    if request.META.get('HTTP_REFERER'):
        r = HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        r.set_cookie('django_language', lang)
        return r
    else:
        return HttpResponseRedirect('/')


def search(request):
    # TODO bracelets filter
    url = request.get_full_path()
    if url.find("page") > -1:
            url = url[url.find("&"):]
    else:
        url = "&" + url[url.find("?") + 1:]

    context = get_context(request)
    context.update({'category': request.GET['category'],
                    'difficulty': request.GET['difficulty'],
                    'rate': request.GET['rate'],
                    'color': request.GET['color'],
                    'orderby': request.GET['orderby'],
                    'categories': BraceletCategory.objects.all(),
                    'photo': 'photo' in request.GET,

templates/common/about.html
{% extends "template.html" %}
{% load i18n %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/static.css' %}"
        type="text/css">
    <script type="text/javascript">
        $(document).ready(function(){
            $('.active').removeClass('active');
            $('#top-about').addClass('active');
        });
    </script>
{% endblock %}
{% block content %}
    {% if contactform.errors %}
        {% trans 'There are some errors in form.' %}

        </div>
        <div class="spacer"></div>
        <div class="box">
    {% endif %}
    {% if LANGUAGE_CODE == 'pl' %}
        <h2>O stronie</h2>
        <hr />
        <p>Strona powstała, aby dzielić się stworzonymi przeze mnie pracami
            i wzorami. W tej wersji aplikacji i Ty możesz dzielić się Twoimi
            pracami.</p>
        <p>Serwis umożliwia dodawanie nowych wzorów przez wygodny
            generator, a potem pomoże w zrobieniu bransoletki mówiąc krok po
            kroku, którą nitką na której trzeba zrobić supełek.</p>

        <p>
            Jeśli chcesz się dowiedzieć więcej o Ohiboce i o mnie - przejdź do <a
                href="http://blog.ohiboka.com/o-nas-2/">tej strony na blogu</a>.
        </p>
        Jeśli znalazłbyś jakiś błąd lub miałbyś sugestie dotyczące strony,
        możesz do mnie napisać. {% else %}
        <h2>About page</h2>
        <hr />
        <p>Page was created to share my work and patterns. In this version
            of application you can share your works, too.</p>
        <p>Service allows you to add new patterns through comfortable
            generator, and then help in making bracelets by showing step by step
            instructions which two strings we need to do knot.</p>
        <p>
            If you want to know more about Ohiboka and me - go to <a
                href="http://blog.ohiboka.com/o-nas-2/">this page on blog</a> (only
            in polish)
        </p>
        If you find any errors or have any ideas, you can sent me an email.
    {% endif %}
    <h2>{% trans "Contact form" %}</h2>
    <hr />
    <form action="/about/" method="post" id="contact-form" class='form-horizontal'>
        {% csrf_token %}
        <fieldset>
            <div
                class="control-group
                  {% if contactform.subject.errors %}
                      error
                  {% endif %}
                      ">
                <label for="id_subject" class="control-label">{% trans contactform.subject.label %}</label>
                <div class="controls">
                    <span class="field">{{ contactform.subject }}</span>
                    {% if contactform.subject.errors %}
                        <span class="help-inline">{% trans 'This field is required' %}</span>
                    {% endif %}
                </div>
            </div>
            <div class="control-group
                  {% if contactform.sender.errors %}
                      error
                  {% endif %}
                  ">
                <label for="id_sender" class="control-label">{% trans contactform.sender.label %}</label>
                <div class="controls">
                    <span class="field">{{ contactform.sender }}</span>
                    {% if contactform.sender.errors %}
                        <span class="help-inline">{% trans 'This field is required' %}</span>
                    {% endif %}
                </div>
            </div>
            <div
                class="control-group
                  {% if contactform.message.errors %}
                      error
                  {% endif %}
                      ">
                <label for="id_message" class="control-label">{% trans contactform.message.label %}</label>
                <div class="controls">
                    <span class="field">{{ contactform.message }}</span>
                    {% if contactform.message.errors %}
                        <span class="help-inline">
                        {% trans 'This field is required' %}</span>
                    {% endif %}
                </div>
            </div>
            <div class="control-group">{{ captcha|safe }}</div>
            <div class="control-group">
                <div class="controls">
                    <input class='btn btn-primary' type="submit" value="{% trans 'Send message' %}" />
                </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

templates/common/bracelet_box_partial.html
{% load i18n %}
{% load static %}
<div class="pattern-box">
	<div class="pattern {% cycle 'pattern-odd' 'pattern-even' %}"
		id="pattern{{ bracelet.id }}">
		<a href="/bracelet/{{ bracelet.url }}">
			<div class="pattern-thumb">
				<img src="{% static 'media/bracelet_thumbs/' %}{{ bracelet.photo.name }}" 
/>
			</div>
			<div class="pattern-info">
				{% if bracelet.now %} <i class="icon-new">&nbsp;</i> <br /> {%
				endif %}
				<div title={% if bracelet.category.id==
					1 %}
                        "{% trans 'nature' %}"
                    {% else %}
                        {% if
					bracelet.category.id==
					2 %}
                            "{% trans 'text' %}"
                        {% else %}
                            {% if
					bracelet.category.id==
					4 %}
                                "{% trans 'zigzak' %}"
                            {% else %}
                                "{% trans 'another' %}"
                            {% endif %}
                        {% endif %}
                    {% endif %}
                    class="category icon-category{{ bracelet.category.id }}">&nbsp;
				</div>
				<br /> <i class="icon-strings"
					title="{% trans 'Number of strings' %}">&nbsp;</i> {{
				bracelet.nofstrings }} <br /> <i class="icon-heart-full"
					title="{% trans 'Rate' %}">&nbsp;</i> {{ bracelet.short_rate }} <br />
				<i class="icon-difficulty{{ bracelet.difficulty}}"
					title="{% trans 'Difficulty' %}">&nbsp;</i>
			</div>
		</a>
	</div>
	<div class="pattern-details" id="pattern_info{{ bracelet.id }}"
		style="display: none">
		<a href="/bracelet/{{ bracelet.url }}">
			<div class="darken">{{ bracelet.name }}</div>
			<div class="darken" style="margin-top: 48px">{% trans 'by' %}:
				{{ bracelet.user.username }} {% trans 'on' %}: {{ bracelet.date }}</div>
			<div class="darken">
				{% for c in bracelet.colors %}
				<div class="knot" style="background-color: {{c}}"></div>
				{% endfor %}
			</div>
		</a>
	</div>
</div>

templates/common/register.html
{% extends "template.html" %} {% load i18n %} {% load static %}
{% block title %} - Create an account{% endblock %} {% block css %}
<link rel="stylesheet" href="{% static 'css/register.css' %}"
	type="text/css">
<script type="text/javascript">
    $(document).ready(function(){
        $('.active').removeClass('active');
        $('#top-register').addClass('active');
    });
</script>
{% endblock %} {% block content %}
<h1>{% trans 'Create an account' %}</h1>
<hr />

<form action="" method="post" id="registerForm"
	class='form-horizontal span4'>
	{% csrf_token %}
	<fieldset>
		{{ form.non_field_errors }} {% for field in form %}
		<div class="control-group">
			<label class="control-label">{{ field.label }}</label>
			<div class="controls">{{ field }}</div>
			<p class="info">{{ field.help_text }}</p>
		</div>
		{% endfor %}
		<div class="control-group">{{ captcha|safe }}</div>
		<div class="control-group">
			<p style="margin: 10px 0;">
				<small>{% trans 'By clicking button below, you accept' %} <a
					href="/privacypolicy/">{% trans 'our privacy policy' %}</a></small>
			</p>
			<div class="controls">
				<button class='btn btn-primary'>{% trans 'Create new
					account' %}</button>
			</div>
			<p class="info">{{ field.help_text }}</p>
		</div>
	</fieldset>
</form>
<div class="facebook_login span4">
	<p style="margin: 10px 0;">{% trans 'Save your time - login with
		facebook' %}</p>
	<button onclick="location.href='/facebook_login'">&nbsp;</button>
</div>
<div class="clearfix"></div>
<script language="Javascript" type="text/javascript">
          $('.field > input').focus(function() {
              $(this).parent().next(".info").fadeIn("slow");
          });
          $('.field > input').focusout(function() {
              $(this).parent().next(".info").fadeOut("slow");
          });
    </script>
{% endblock %}

templates/common/user.html
{% extends "template.html" %}
{% load i18n %}
{% load static %}
{% block title %} - {% trans 'User page' %} - {{ user_content.username }}{% endblock %}

{%block css %}
<link rel="stylesheet"
	href="{% static 'css/jquery.lightbox-0.5.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/bracelet.css' %}"
	type="text/css">
<link rel="stylesheet" href="{% static 'css/home.css' %}"
	type="text/css">
<link rel="stylesheet" href="{% static 'css/userprofile.css' %}"
	type="text/css">
<script src="{% static 'js/jquery.lightbox-0.5.pack.js' %}"
	type="text/javascript"></script>
<script type="text/javascript">
	$(document).ready(function(){
		$('.pattern').hover(function() {
			$('.pattern-details').hide();
			$('#pattern_info'+$(this).attr('id').substring(7)).show();
		});
		$('.pattern-box').hover(function() {}, function() {
			$('.pattern-details').hide();
		});
		$('.photo a').lightBox({
			imageLoading: {{STATIC_URL}}+'gfx/lightbox-ico-loading.gif',
			imageBtnClose: {{STATIC_URL}}+'gfx/lightbox-btn-close.gif',
			imageBtnPrev: {{STATIC_URL}}+'gfx/lightbox-btn-prev.gif',
			imageBtnNext: {{STATIC_URL}}+'gfx/lightbox-btn-next.gif',
		});
	});
</script>
{% endblock %}

{% block content %}
<big><h2>
		{% trans 'Content added by' %} <b>{{ user_content.username }}</b>
	</h2></big>

{% if bracelets %}
<h3>{% trans "Bracelets" %}</h3>

<hr />
{% for bt in bracelets %}
<div class="pattern-box">
	<div class="pattern {% cycle 'pattern-odd' 'pattern-even' %}"
		id="pattern{{ bt.id }}">
		<a href="/bracelet/{{ bt.url }}">
			<div class="pattern-thumb">
				<img src="{% static 'media/bracelet_thumbs/' %}{{ bt.photo.name }}" />
			</div>
			<div class="pattern-info">
				{% if bt.now %} <i class="icon-new">&nbsp;</i> <br /> {% endif %}
				<div title={% if bt.category.id == 1 %}
		    	    			"{% trans 'nature' %}"
		    	    		{% else %}
		    	    			{% if bt.category.id == 2 %}
		    	    				"{% trans 'text' %}"
		    	    			{% else %}
		    	    				{% if bt.category.id == 4 %}
		    	    					"{% trans 'zigzak' %}"
		    	    				{% else %}
		    	    					"{% trans 'another' %}"
		    	    				{% endif %}
		    	    			{% endif %}
		    	    		{% endif %}
		    	    		 class="category category{{ bt.category.id }}">&nbsp;
				</div>
				<br /> <i class="icon-strings"
					title="{% trans 'Number of strings' %}">&nbsp;</i> {{ bt.nofstrings }} <br /> <i class="icon-star2" title="{% trans 'Rate' %}">&nbsp;</i>
				{{ bt.short_rate }} <br /> <i
					class="icon-difficulty{{ bt.difficulty}}"
					title="{% trans 'Difficulty' %}">&nbsp;</i>
			</div>
		</a>
	</div>
	<div class="pattern-details" id="pattern_info{{ bt.braceletid }}"
		style="display: none">
		<a href="/bracelet/{{ bt.braceletid }}">
			<div class="darken">{{ bt.name }}</div>
			<div class="darken" style="margin-top: 48px">{% trans 'by' %}:
				{{ bt.user.username }} {% trans 'on' %}: {{ bt.date }}</div>
			<div class="darken">
				{% for c in bt.colors %}
				<div class="knot" style="background-color: {{c}}"></div>
				{% endfor %}
			</div>

		</a>
	</div>
</div>
{% endfor %} {% endif %} 

{% if photos %}
<div id="user_photos">
	<h3>{% trans 'Photos' %}</h3>
	<hr />
	{% for photo in photos %}
	<div class="photo">
		<a href="{% static 'media/images/' %}{{ photo.name }}"><img
			src="{% static 'media/bracelet_thumbs/' %}{{ photo.name }}" /></a> <a
			href="/bracelet/{{ photo.bracelet.id }}">{{photo.bracelet.name}}</a>
	</div>
	{% endfor %}
</div>
{% endif %} {% endblock %}